# Sample workflow for building and deploying a Nuxt site to GitHub Pages
#
# To get started with Nuxt see: https://nuxtjs.org/docs/get-started/installation
#
name: Deploy to Deno

on:
  # Runs on pushes targeting the default branch
  # Disabled at the moment
  # push:
  #   branches: ["main"]

  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          cache: pnpm
      - run: pnpm install
      - name: "Create env file"
        run: |
          touch .env
          echo NUXT_PUBLIC_DROPBOX_TOKEN=${{ secrets.NUXT_PUBLIC_DROPBOX_TOKEN }} >> .env
          cat .env
      - run: pnpm build
        env:
          NITRO_PRESET: deno_deploy
          NUXT_PUBLIC_DROPBOX_TOKEN: |
            ${{ secrets.NUXT_PUBLIC_DROPBOX_TOKEN }}
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: nikechukwu
          entrypoint: server/index.ts
          root: .output
          env: |
            NUXT_PUBLIC_DROPBOX_TOKEN=${{ secrets.NUXT_PUBLIC_DROPBOX_TOKEN }}
